Repository kartash-me/Memory-Keeper, pull requests merged in 2025-04, with the labels that each got.

#4 🔗 feat: setup initial backend structure
  app.py
Labels: backend

#5 ⭐️ feat: implement initial frontend structure
  static/css/bootstrap.min.css
  static/css/bootstrap.min.css.map
  static/js/bootstrap.min.js
  static/js/bootstrap.min.js.map
  templates/base.html
  templates/includes/footer.html
  templates/includes/header.html
Labels: frontend

#7 Enhance Navbar and Add Routes for Authentication
  app.py
  templates/includes/header.html
Labels: backend, frontend

#18 Refactor app structure and add login/register functionality
  app.py
  forms.py
Labels: backend

#20 🔄 refactor(registration): overhaul multi-step flow & enforce unique v…
  .gitignore
  app.py
  db/memory_keeper.db
  forms.py
  mega_validators.py
  templates/login.html
  templates/register.html
Labels: backend, database
