Repository kartash-me/Memory-Keeper, pull requests merged in 2025-05, with the labels that each got.

#21 Enhance app structure, media handling, and frontend foundation
  .gitignore
  Memory_Keeper_TZ.md
  README.md
  app.py
  data/db_session.py
  data/users.py
  db/memory_keeper.db
  forms.py
  mega_validators.py
  requirements.txt
  static/css/bootstrap.min.css
  static/css/bootstrap.min.css.map
  static/img/userpic.png
  static/js/bootstrap.bundle.min.js
  static/js/bootstrap.bundle.min.js.map
  static/js/bootstrap.min.js
  static/js/bootstrap.min.js.map
  templates/base.html
  templates/includes/header.html
  templates/main/home.html
  templates/promotion/index.html
  templates/promotion/login.html
  templates/promotion/register.html
Labels: backend, frontend

#23 Add user avatars, profile page, and unify form templates
  app.py
  data/users.py
  static/css/form.css
  templates/includes/header.html
  templates/main/home.html
  templates/main/profile.html
  templates/promotion/form.html
  templates/promotion/login.html
  templates/promotion/register.html
Labels: backend, frontend

#24 Kapusta develop
  app.py
  data/__all_models.py
  data/photo.py
  data/users.py
  forms.py
  mega_validators.py
  requirements.txt
Labels: enhancement, backend, database

#28 🎯 Feature & Refactor: Comprehensive User Profile System & File Handling Improvements
  app.py
  data/photo.py
  data/users.py
  forms.py
  mega_validators.py
  requirements.txt
  static/css/profile.css
  static/ico/logout.png
  static/img/avatar.png
  static/js/profile.js
  templates/base.html
  templates/includes/header.html
  templates/main/profile.html
  templates/promotion/form.html
Labels: backend, frontend, database

#29 🛠️ Enhance & Refactor: User Profile Management & File Handling Improvements
  app.py
  forms.py
  functions.py
  static/css/profile.css
  templates/main/profile.html
Labels: backend, frontend

#30 feat(core): photo geotagging, interactive map & secure auth overhaul
  app.py
  data/photo.py
  data/users.py
  forms.py
  functions.py
  mega_validators.py
  requirements.txt
  template.env
  templates/main/home.html
  templates/main/upload.html
Labels: bug, backend

#34 ✨ chore: project initialization and database setup
  .gitignore
  app.py
  data/db_session.py
  data/photo.py
  data/users.py
  forms.py
  functions.py
  mega_validators.py
  passenger_wsgi.py
  requirements.txt
  static/css/account.css
  static/css/map.css
  static/js/account.js
  static/js/map.js
  template.env
  templates/base.html
  templates/includes/balloon.html
  templates/includes/header.html
  templates/main/account.html
  templates/main/gallery.html
  templates/main/home.html
  templates/main/upload.html
  templates/promotion/form.html
  templates/promotion/home.html
Labels: backend, frontend, database
